TYRE HUNT — write sw.js into your APP repo folder

Run ONE LINE AT A TIME.
(Use whatever folder your app's index.html lives in — the example below
 assumes ~/Desktop/tyrehunt. Change it if yours is elsewhere.)

cd ~/Desktop/tyrehunt

echo 'LyogVFlSRSBIVU5UIHNlcnZpY2Ugd29ya2VyCiAqCiAqIERFTElCRVJBVEVMWSBQVVNILU9OTFkuIFRoZXJlIGlzIG5vIGZldGNoIGhhbmRsZXIgYW5kIG5vIGNhY2hpbmcgaGVyZS4KICogVGhlIGFwcCBzaGlwcyBhcyBhIHNpbmdsZSBmaWxlIHRoYXQgY2hhbmdlcyBzZXZlcmFsIHRpbWVzIGEgZGF5LCBhbmQgYQogKiBjYWNoaW5nIHNlcnZpY2Ugd29ya2VyIGlzIHRoZSBjbGFzc2ljIHdheSB0byBzZXJ2ZSBhIHN0YWxlIGJ1aWxkIHRvCiAqIHVzZXJzIHdobyB0aGVuIHJlcG9ydCBidWdzIHlvdSBhbHJlYWR5IGZpeGVkLiBJZiBvZmZsaW5lIGNhY2hpbmcgaXMKICogZXZlciB3YW50ZWQsIGl0IHNob3VsZCBiZSBhZGRlZCBrbm93aW5nbHksIHdpdGggYSB2ZXJzaW9uZWQgY2FjaGUgYW5kCiAqIGEgc2tpcFdhaXRpbmcgc3Rvcnkg4oCUIG5vdCBhcyBhIHNpZGUgZWZmZWN0IG9mIGFkZGluZyBub3RpZmljYXRpb25zLgogKi8KCnNlbGYuYWRkRXZlbnRMaXN0ZW5lcigiaW5zdGFsbCIsIChlKSA9PiB7CiAgc2VsZi5za2lwV2FpdGluZygpOwp9KTsKCnNlbGYuYWRkRXZlbnRMaXN0ZW5lcigiYWN0aXZhdGUiLCAoZSkgPT4gewogIGUud2FpdFVudGlsKHNlbGYuY2xpZW50cy5jbGFpbSgpKTsKfSk7CgpzZWxmLmFkZEV2ZW50TGlzdGVuZXIoInB1c2giLCAoZXZlbnQpID0+IHsKICBsZXQgZGF0YSA9IHt9OwogIHRyeSB7IGRhdGEgPSBldmVudC5kYXRhID8gZXZlbnQuZGF0YS5qc29uKCkgOiB7fTsgfSBjYXRjaCAoZSkgeyBkYXRhID0ge307IH0KCiAgY29uc3QgdGl0bGUgPSBkYXRhLnRpdGxlIHx8ICJUWVJFIEhVTlQiOwogIGNvbnN0IG9wdGlvbnMgPSB7CiAgICBib2R5OiBkYXRhLmJvZHkgfHwgIiIsCiAgICBpY29uOiAiaWNvbi0xOTIucG5nIiwKICAgIGJhZGdlOiAiaWNvbi0xOTIucG5nIiwKICAgIHRhZzogZGF0YS50YWcgfHwgInR5cmVodW50IiwKICAgIHJlbm90aWZ5OiBmYWxzZSwKICAgIGRhdGE6IHsgdXJsOiBkYXRhLnVybCB8fCAiLyIgfSwKICAgIHZpYnJhdGU6IFsxMl0sCiAgfTsKICBldmVudC53YWl0VW50aWwoc2VsZi5yZWdpc3RyYXRpb24uc2hvd05vdGlmaWNhdGlvbih0aXRsZSwgb3B0aW9ucykpOwp9KTsKCnNlbGYuYWRkRXZlbnRMaXN0ZW5lcigibm90aWZpY2F0aW9uY2xpY2siLCAoZXZlbnQpID0+IHsKICBldmVudC5ub3RpZmljYXRpb24uY2xvc2UoKTsKICBjb25zdCB0YXJnZXQgPSAoZXZlbnQubm90aWZpY2F0aW9uLmRhdGEgJiYgZXZlbnQubm90aWZpY2F0aW9uLmRhdGEudXJsKSB8fCAiLyI7CiAgZXZlbnQud2FpdFVudGlsKAogICAgc2VsZi5jbGllbnRzLm1hdGNoQWxsKHsgdHlwZTogIndpbmRvdyIsIGluY2x1ZGVVbmNvbnRyb2xsZWQ6IHRydWUgfSkudGhlbigobGlzdCkgPT4gewogICAgICAvLyBmb2N1cyBhbiBvcGVuIHRhYiBpZiB0aGVyZSBpcyBvbmUsIHJhdGhlciB0aGFuIG9wZW5pbmcgYSBkdXBsaWNhdGUKICAgICAgZm9yIChjb25zdCBjbGllbnQgb2YgbGlzdCkgewogICAgICAgIGlmICgiZm9jdXMiIGluIGNsaWVudCkgewogICAgICAgICAgY2xpZW50Lm5hdmlnYXRlKHRhcmdldCkuY2F0Y2goKCkgPT4ge30pOwogICAgICAgICAgcmV0dXJuIGNsaWVudC5mb2N1cygpOwogICAgICAgIH0KICAgICAgfQogICAgICBpZiAoc2VsZi5jbGllbnRzLm9wZW5XaW5kb3cpIHJldHVybiBzZWxmLmNsaWVudHMub3BlbldpbmRvdyh0YXJnZXQpOwogICAgfSkKICApOwp9KTsK' | base64 --decode > sw.js

wc -c sw.js

The last line should print about 1713.
Then commit/upload sw.js to the app repo alongside index.html.
